#!/usr/bin/env python3
"""
inject_test_logs.py — WATCH_LOGS Multi-Service Test Log Injector (ECS Edition)
Injects fake log entries with Elastic Common Schema (ECS) event fields for SSH, FTP,
Telnet, HTTP, SMTP, DNS, MySQL, SMB, SNMP, and RDP into Elasticsearch to trigger
all detection rules and correlations.

ECS Fields Added:
  event.category  — "authentication", "network", "intrusion_detection", "process", "web", "email"
  event.type      — "start", "end", "info", "error", "denied"
  event.outcome   — "success", "failure", "unknown"
  event.action    — specific action like "ssh_login", "ftp_login", etc.
  event.severity  — 1 (low), 2 (medium), 3 (high), 4 (critical)

Run on the Kali VM:
    python3 inject_test_logs.py
"""

import uuid
import os, json
from datetime import datetime, timezone, timedelta
from elasticsearch import Elasticsearch
import urllib3

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# ── Config ─────────────────────────────────────────────────────────────────
ES_HOST   = "https://localhost:9200"
ES_USER   = "elastic"
ES_PASS   = "Watchlogs@69"
TEST_HOST = "kalihost"                         # must match your actual hostname

# Always use today's date so it falls within the siem-logs-* wildcard
TODAY_INDEX = "siem-logs-" + datetime.now(timezone.utc).strftime("%Y.%m.%d")

# ── Connect ─────────────────────────────────────────────────────────────────
es = Elasticsearch(ES_HOST, basic_auth=(ES_USER, ES_PASS), verify_certs=False)

def now_iso(offset_seconds=0):
    """Return ISO-8601 UTC timestamp, optionally offset into the past (still recent)."""
    ts = datetime.now(timezone.utc) - timedelta(seconds=offset_seconds)
    return ts.strftime("%Y-%m-%dT%H:%M:%S.000Z")

def is_host_isolated(host):
    iso_file = os.path.join(os.path.dirname(os.path.abspath(__file__)), "backend", "isolated_hosts.json")
    if os.path.exists(iso_file):
        try:
            with open(iso_file, "r") as f:
                data = json.load(f)
                # Support both dict (new) and list (legacy) formats
                if isinstance(data, dict):
                    return host in data
                elif isinstance(data, list):
                    return host in data
        except:
            pass
    return False

def inject(message, offset_seconds=0, process="sshd", index=None, src_ip="10.10.10.99",
           event_category="process", event_type="info", event_outcome="unknown",
           event_action="", event_severity=1):
    """Inject a log document with ECS event fields into Elasticsearch."""
    # If the endpoint is isolated, simulate that network logs are no longer generated by this system.
    if is_host_isolated(TEST_HOST):
        return "dropped (host network blocked)"

    idx = index or TODAY_INDEX
    doc = {
        "@timestamp": now_iso(offset_seconds),
        "message":    message,
        "host": {
            "hostname": TEST_HOST,
            "name":     TEST_HOST,
            "ip":       ["192.168.158.131"]
        },
        "log": {
            "syslog": {
                "appname":  process,
                "facility": {"code": 4}
            }
        },
        "process": {
            "name": process,
            "pid":  1234
        },
        "source": {
            "ip": src_ip
        },
        "event": {
            "category": event_category,
            "type":     event_type,
            "outcome":  event_outcome,
            "action":   event_action,
            "severity": event_severity
        },
        "tags": ["test-injection"]
    }
    res = es.index(index=idx, id=str(uuid.uuid4()), document=doc)
    return res["result"]


print("=" * 70)
print("  WATCH_LOGS — Multi-Service Detection Test Injector (ECS Edition)")
print(f"  Target index : {TODAY_INDEX}")
print(f"  Test host    : {TEST_HOST}")
print("=" * 70)


# ════════════════════════════════════════════════════════════════
# SECTION A — SSH Rules
# ════════════════════════════════════════════════════════════════

print("\n── SECTION A: SSH Detections ───────────────────────────────")

# Rule: SSH_BRUTE_FORCE — 5+ "Failed password" in 300s
print("\n[A1] SSH Brute Force (8 failed auth events)...")
for i in range(8):
    msg = f"Failed password for invalid user admin from 10.10.10.99 port {50000 + i} ssh2"
    r   = inject(msg, offset_seconds=i * 20,
                 event_category="authentication", event_type="start",
                 event_outcome="failure", event_action="ssh_login", event_severity=4)
    print(f"     [{i+1}/8] {r}")

# Rule: ROOT_SESSION
print("\n[A2] Root Session (1 event)...")
r = inject("pam_unix(sshd:session): session opened for user root by (uid=0)", offset_seconds=5,
           event_category="process", event_type="start",
           event_outcome="success", event_action="session_start", event_severity=3)
print(f"     {r}")

# Rule: INVALID_USER
print("\n[A3] Invalid User attempts (3 events)...")
for i, user in enumerate(["ghost", "test", "admin123"]):
    msg = f"Invalid user {user} from 10.10.10.88 port {60000 + i} ssh2"
    r   = inject(msg, offset_seconds=i * 10,
                 event_category="authentication", event_type="start",
                 event_outcome="failure", event_action="ssh_login", event_severity=4)
    print(f"     [{i+1}/3] {r}")

# Rule: SUDO_ABUSE — 3+ "sudo" in 120s
print("\n[A4] Sudo Abuse (4 sudo commands)...")
for i in range(4):
    msg = f"sudo: kalihost : TTY=pts/{i} ; PWD=/home/kalihost ; USER=root ; COMMAND=/bin/bash"
    r   = inject(msg, offset_seconds=i * 15, process="sudo",
                 event_category="process", event_type="start",
                 event_outcome="success", event_action="sudo_command", event_severity=3)
    print(f"     [{i+1}/4] {r}")

# Rule: SSH_LOGIN_SUCCESS — "Accepted password"
print("\n[A5] SSH Login Success (1 event)...")
r = inject("Accepted password for kalihost from 10.10.10.99 port 51234 ssh2", offset_seconds=2,
           event_category="authentication", event_type="start",
           event_outcome="success", event_action="ssh_login", event_severity=2)
print(f"     {r}")


# ════════════════════════════════════════════════════════════════
# SECTION B — FTP Rules
# ════════════════════════════════════════════════════════════════

print("\n── SECTION B: FTP Detections ───────────────────────────────")

# Rule: FTP_BRUTE_FORCE — 5+ "FAIL LOGIN" in 300s
print("\n[B1] FTP Brute Force (6 failed login events)...")
for i in range(6):
    msg = f"vsftpd: pam_unix(vsftpd:auth): FAIL LOGIN from 10.10.10.77 - user admin{i}"
    r   = inject(msg, offset_seconds=i * 20, process="vsftpd", src_ip="10.10.10.77",
                 event_category="authentication", event_type="start",
                 event_outcome="failure", event_action="ftp_login", event_severity=4)
    print(f"     [{i+1}/6] {r}")

# Rule: FTP_LOGIN_SUCCESS
print("\n[B2] Successful FTP Login (1 event)...")
r = inject("vsftpd: FTP session opened for user kalihost from 10.10.10.77", offset_seconds=2,
           process="vsftpd", src_ip="10.10.10.77",
           event_category="authentication", event_type="start",
           event_outcome="success", event_action="ftp_login", event_severity=2)
print(f"     {r}")

# Rule: FTP_ANONYMOUS_LOGIN
print("\n[B3] Anonymous FTP Login (1 event)...")
r = inject("vsftpd: ANONYMOUS FTP LOGIN from 10.10.10.66, guest", offset_seconds=5,
           process="vsftpd", src_ip="10.10.10.66",
           event_category="authentication", event_type="start",
           event_outcome="success", event_action="ftp_anonymous_login", event_severity=3)
print(f"     {r}")


# ════════════════════════════════════════════════════════════════
# SECTION C — Telnet Rules
# ════════════════════════════════════════════════════════════════

print("\n── SECTION C: Telnet Detections ────────────────────────────")

# Rule: TELNET_AUTH_FAILURE — 3+ failures in 300s
print("\n[C1] Telnet Auth Failures (4 events)...")
for i in range(4):
    msg = f"in.telnetd: LOGIN FAILURE from 10.10.10.55 for user root{i}"
    r   = inject(msg, offset_seconds=i * 15, process="in.telnetd", src_ip="10.10.10.55",
                 event_category="authentication", event_type="start",
                 event_outcome="failure", event_action="telnet_login", event_severity=4)
    print(f"     [{i+1}/4] {r}")

# Rule: TELNET_LOGIN_SUCCESS
print("\n[C2] Telnet Login Success (1 event)...")
r = inject("LOGIN ON pts/3 BY testuser FROM 10.10.10.55", offset_seconds=2,
           process="in.telnetd", src_ip="10.10.10.55",
           event_category="authentication", event_type="start",
           event_outcome="success", event_action="telnet_login", event_severity=2)
print(f"     {r}")


# ════════════════════════════════════════════════════════════════
# SECTION D — HTTP / Web Attack Rules
# ════════════════════════════════════════════════════════════════

print("\n── SECTION D: HTTP / Web Detections ────────────────────────")

# Rule: HTTP_AUTH_BYPASS — 10+ 401/403 in 120s
print("\n[D1] HTTP Unauthorized Access Surge (12 events)...")
for i in range(12):
    status = "401 Unauthorized" if i % 2 == 0 else "403 Forbidden"
    msg = f"apache2: {status} - GET /admin/config from 10.10.10.44 - {status}"
    r   = inject(msg, offset_seconds=i * 8, process="apache2", src_ip="10.10.10.44",
                 event_category="web", event_type="denied",
                 event_outcome="failure", event_action="http_request", event_severity=4)
    print(f"     [{i+1}/12] {r}")

# Rule: HTTP_WEB_ATTACK
print("\n[D2] Web Application Attacks (3 events)...")
attacks = [
    ("apache2: [error] SQL injection attempt detected in query: ' UNION SELECT * FROM users --", "apache2", "sql_injection"),
    ("apache2: [alert] directory traversal attempt: GET /../../etc/passwd from 10.10.10.44", "apache2", "directory_traversal"),
    ("nginx: [warn] XSS attempt blocked: <script>alert('xss')</script> in POST /comment", "nginx", "xss_attack"),
]
for i, (msg, proc, action) in enumerate(attacks):
    r = inject(msg, offset_seconds=i * 30, process=proc, src_ip="10.10.10.44",
               event_category="intrusion_detection", event_type="denied",
               event_outcome="failure", event_action=action, event_severity=3)
    print(f"     [{i+1}/3] {r}")


# ════════════════════════════════════════════════════════════════
# SECTION E — SMTP Rules
# ════════════════════════════════════════════════════════════════

print("\n── SECTION E: SMTP Detections ──────────────────────────────")

# Rule: SMTP_RELAY_ABUSE — 5+ relay denied in 300s
print("\n[E1] SMTP Relay Abuse (6 events)...")
for i in range(6):
    msg = f"postfix/smtpd: NOQUEUE: reject: RCPT from unknown[10.10.10.33]: 554 relay denied for user{i}@evil.com"
    r   = inject(msg, offset_seconds=i * 25, process="postfix", src_ip="10.10.10.33",
                 event_category="email", event_type="denied",
                 event_outcome="failure", event_action="smtp_relay", event_severity=4)
    print(f"     [{i+1}/6] {r}")


# ════════════════════════════════════════════════════════════════
# SECTION F — DNS Rules
# ════════════════════════════════════════════════════════════════

print("\n── SECTION F: DNS Detections ───────────────────────────────")

# Rule: DNS_ZONE_TRANSFER
print("\n[F1] DNS Zone Transfer Attempt (2 events)...")
dns_msgs = [
    "named: zone transfer 'example.com/AXFR' denied from 10.10.10.22",
    "named: client 10.10.10.22: AXFR request for zone 'internal.corp'",
]
for i, msg in enumerate(dns_msgs):
    r = inject(msg, offset_seconds=i * 30, process="named", src_ip="10.10.10.22",
               event_category="network", event_type="denied",
               event_outcome="failure", event_action="dns_zone_transfer", event_severity=3)
    print(f"     [{i+1}/2] {r}")

# Rule: DNS_QUERY_ABUSE — 20+ in 60s
print("\n[F2] DNS Query Flood (25 events)...")
for i in range(25):
    msg = f"named: client 10.10.10.22: query (cache) denied for domain{i}.evil.com"
    r   = inject(msg, offset_seconds=i * 2, process="named", src_ip="10.10.10.22",
                 event_category="network", event_type="denied",
                 event_outcome="failure", event_action="dns_query", event_severity=2)
    print(f"     [{i+1}/25] {r}")


# ════════════════════════════════════════════════════════════════
# SECTION G — MySQL / Database Rules
# ════════════════════════════════════════════════════════════════

print("\n── SECTION G: MySQL/Database Detections ────────────────────")

# Rule: MYSQL_AUTH_FAILURE — 5+ in 300s
print("\n[G1] MySQL Auth Failures (6 events)...")
for i in range(6):
    msg = f"mysqld: Access denied for user 'root'@'10.10.10.11' (using password: YES)"
    r   = inject(msg, offset_seconds=i * 20, process="mysqld", src_ip="10.10.10.11",
                 event_category="authentication", event_type="start",
                 event_outcome="failure", event_action="mysql_login", event_severity=4)
    print(f"     [{i+1}/6] {r}")


# ════════════════════════════════════════════════════════════════
# SECTION H — SMB Rules
# ════════════════════════════════════════════════════════════════

print("\n── SECTION H: SMB Detections ───────────────────────────────")

# Rule: SMB_BRUTE_FORCE — 5+ in 300s
print("\n[H1] SMB Brute Force (6 events)...")
for i in range(6):
    msg = f"smbd: NT_STATUS_LOGON_FAILURE from 10.10.10.88 for user admin{i} on share \\\\server\\files"
    r   = inject(msg, offset_seconds=i * 20, process="smbd", src_ip="10.10.10.88",
                 event_category="authentication", event_type="start",
                 event_outcome="failure", event_action="smb_login", event_severity=4)
    print(f"     [{i+1}/6] {r}")


# ════════════════════════════════════════════════════════════════
# SECTION I — SNMP Rules
# ════════════════════════════════════════════════════════════════

print("\n── SECTION I: SNMP Detections ──────────────────────────────")

# Rule: SNMP_AUTH_FAILURE
print("\n[I1] SNMP Auth Failure (3 events)...")
snmp_msgs = [
    "snmpd: authenticationFailure trap from 10.10.10.77 with community string 'public'",
    "snmpd: bad community string from 10.10.10.77 using 'private'",
    "snmpd: authenticationFailure from 10.10.10.77 - unknown community 'test123'",
]
for i, msg in enumerate(snmp_msgs):
    r = inject(msg, offset_seconds=i * 30, process="snmpd", src_ip="10.10.10.77",
               event_category="authentication", event_type="start",
               event_outcome="failure", event_action="snmp_auth", event_severity=4)
    print(f"     [{i+1}/3] {r}")


# ════════════════════════════════════════════════════════════════
# SECTION J — Correlation Engine Sequences
# ════════════════════════════════════════════════════════════════

print("\n── SECTION J: Correlation Engine Sequences ─────────────────")

# Correlation: BRUTE_FORCE_SUCCESS (SSH)
print("\n[J1] SSH Brute Force → Success sequence...")
for i in range(5):
    msg = f"Failed password for root from 10.10.10.77 port {55000 + i} ssh2"
    r   = inject(msg, offset_seconds=300 - i * 30,
                 event_category="authentication", event_type="start",
                 event_outcome="failure", event_action="ssh_login", event_severity=4)
    print(f"     [{i+1}/5] {r}")
r = inject("Accepted password for kalihost from 10.10.10.77 port 55999 ssh2", offset_seconds=10,
           event_category="authentication", event_type="start",
           event_outcome="success", event_action="ssh_login", event_severity=2)
print(f"     [6/6] {r} — sequence complete")

# Correlation: FTP_BRUTE_FORCE_SUCCESS
print("\n[J2] FTP Brute Force → Success sequence...")
for i in range(4):
    msg = f"vsftpd: FAIL LOGIN from 10.10.10.55 - user ftpuser{i}"
    r   = inject(msg, offset_seconds=200 - i * 30, process="vsftpd", src_ip="10.10.10.55",
                 event_category="authentication", event_type="start",
                 event_outcome="failure", event_action="ftp_login", event_severity=4)
    print(f"     [{i+1}/4] {r}")
r = inject("vsftpd: FTP session opened for user ftpuser from 10.10.10.55", offset_seconds=5,
           process="vsftpd", src_ip="10.10.10.55",
           event_category="authentication", event_type="start",
           event_outcome="success", event_action="ftp_login", event_severity=2)
print(f"     [5/5] {r} — sequence complete")

# Correlation: SUDO_ABUSE_ROOT_SESSION
print("\n[J3] Sudo Abuse → Root Session sequence...")
for i in range(3):
    msg = f"sudo: kalihost : TTY=pts/{i+4} ; PWD=/root ; USER=root ; COMMAND=/usr/bin/id"
    r   = inject(msg, offset_seconds=200 - i * 30, process="sudo",
                 event_category="process", event_type="start",
                 event_outcome="success", event_action="sudo_command", event_severity=3)
    print(f"     [{i+1}/3] {r}")
r = inject("pam_unix(su:session): session opened for user root by kalihost(uid=1000)", offset_seconds=10,
           event_category="process", event_type="start",
           event_outcome="success", event_action="session_start", event_severity=3)
print(f"     [4/4] {r} — sequence complete")

# Correlation: WEB_ATTACK_PRIVESC
print("\n[J4] Web Attack → Privilege Escalation sequence...")
for i in range(4):
    status = "401 Unauthorized" if i % 2 == 0 else "403 Forbidden"
    msg = f"apache2: {status} - POST /admin/shell from 10.10.10.44"
    r   = inject(msg, offset_seconds=200 - i * 30, process="apache2", src_ip="10.10.10.44",
                 event_category="web", event_type="denied",
                 event_outcome="failure", event_action="http_request", event_severity=4)
    print(f"     [{i+1}/4] {r}")
r = inject("sudo: www-data : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/bash", offset_seconds=5,
           process="sudo",
           event_category="process", event_type="start",
           event_outcome="success", event_action="sudo_command", event_severity=3)
print(f"     [5/5] {r} — web exploit to root (sequence complete)")

# Correlation: DNS_RECON_THEN_ATTACK
print("\n[J5] DNS Recon → Service Attack sequence...")
r = inject("named: zone transfer 'corp.local/AXFR' denied from 10.10.10.22", offset_seconds=250,
           process="named", src_ip="10.10.10.22",
           event_category="network", event_type="denied",
           event_outcome="failure", event_action="dns_zone_transfer", event_severity=3)
print(f"     [1/4] {r} — DNS zone transfer")
for i in range(3):
    msg = f"Failed password for admin from 10.10.10.22 port {54000 + i} ssh2"
    r   = inject(msg, offset_seconds=100 - i * 20, src_ip="10.10.10.22",
                 event_category="authentication", event_type="start",
                 event_outcome="failure", event_action="ssh_login", event_severity=4)
    print(f"     [{i+2}/4] {r}")
print("     sequence complete")


# ── Force index refresh so all docs are searchable immediately ──────────────
print("\n⟳  Refreshing index so events are immediately queryable...")
es.indices.refresh(index=TODAY_INDEX)

count = es.count(index=TODAY_INDEX)["count"]
print(f"✓  Index refreshed. Total docs in {TODAY_INDEX}: {count}")

# Quick count of test injections
test_count = es.count(index=TODAY_INDEX, body={"query": {"term": {"tags": "test-injection"}}})["count"]
print(f"✓  Test-injection tagged docs: {test_count}")

print()
print("=" * 70)
print("  Injected ECS-enriched events for: SSH, FTP, Telnet, HTTP, SMTP, DNS,")
print("                                    MySQL, SMB, SNMP + Correlation Sequences")
print()
print("  ECS fields: event.category, event.type, event.outcome,")
print("              event.action, event.severity (1-4)")
print()
print("  Next steps:")
print()
print("  1. Reload rules:")
print("     curl -s -X POST http://localhost:5000/api/rules/reload")
print()
print("  2. Trigger correlation engine:")
print("     curl -s -X POST http://localhost:5000/api/correlations/run | python3 -m json.tool")
print()
print("  3. View fired alerts:")
print("     curl -s http://localhost:5000/api/alerts/rules | python3 -m json.tool")
print("     curl -s http://localhost:5000/api/alerts/correlated | python3 -m json.tool")
print("=" * 70)
